FROM docker.io/library/ubuntu:24.10

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install OpenJDK and wget
RUN apt-get update && \
    apt-get install -y openjdk-23-jre-headless wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JMeter version
ENV JMETER_VERSION=5.6.3

# Download and install JMeter
RUN cd /opt \
    && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz \
    && tar -xzf apache-jmeter-${JMETER_VERSION}.tgz \
    && rm apache-jmeter-${JMETER_VERSION}.tgz
